### ISSUE TITLE
Unhandled rejection Error: Incorrect HTTP method for uri [/randomindex] and method [POST], allowed: [PUT, DELETE, GET, HEAD]

### ISSUE THREAD

**Issue by sugizo** [RaananW/express.js-elasticsearch-autocomplete-demo#5]
$ npm start

> autocompleter@0.0.0 start /Users/sugizo/js/learn/express.js-elasticsearch-autocomplete
> node ./bin/www

Elasticsearch INFO: 2017-11-21T03:21:53Z
  Adding connection to http://localhost:9200/

Unhandled rejection Error: Incorrect HTTP method for uri [/randomindex] and method [POST], allowed: [PUT, DELETE, GET, HEAD]
    at respond (/Users/sugizo/js/learn/express.js-elasticsearch-autocomplete/node_modules/elasticsearch/src/lib/transport.js:264:15)
    at checkRespForFailure (/Users/sugizo/js/learn/express.js-elasticsearch-autocomplete/node_modules/elasticsearch/src/lib/transport.js:223:7)
    at HttpConnector.<anonymous> (/Users/sugizo/js/learn/express.js-elasticsearch-autocomplete/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/sugizo/js/learn/express.js-elasticsearch-autocomplete/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by RaananW** [comment]
What version of elasticsearch are you using?

**Comment by sugizo** [comment]
elasticsearch-6.0.0

**Comment by jreyes88** [comment]
I am getting this issue, too, using elasticsearch-6.1.1

**Comment by RaananW** [comment]
please note, this was written (2 years ago) for elasticsearch 2. Code needs to be modified to fit the new API. 
Whenever I will find the time, I will dive into the new ES API. Not in the near future thou
